#+TITLE: Doom Emacs Configuration
#+AUTHOR: Rajat (wssholmes)
#+DESCRIPTION: Personal Doom Emacs Config.
#+STARTUP: showeverything

* TABLE OF CONTENTS :toc:
- [[#about][ABOUT]]
- [[#themes-and-fonts][THEMES AND FONTS]]
- [[#prettify-symbol][PRETTIFY SYMBOL]]
- [[#org-mode][ORG MODE]]
- [[#gui-tweaks][GUI TWEAKS]]
  - [[#line-numbers][Line Numbers]]
- [[#file-save-and-load][FILE SAVE AND LOAD]]
- [[#custom-keybindings][CUSTOM KEYBINDINGS]]
- [[#evil-mode][EVIL MODE]]
  - [[#window-split][Window Split]]
- [[#flyspell][FLYSPELL]]
- [[#tree-sitter][TREE SITTER]]
- [[#super-save][SUPER SAVE]]
- [[#lsp-mode][LSP MODE]]
- [[#python-lsp-ms][PYTHON LSP MS]]
- [[#go-lsp-gopls][GO LSP (GOPLS)]]
- [[#company][COMPANY]]
- [[#yasnippet][YASNIPPET]]
- [[#eshell][ESHELL]]
- [[#modeline][MODELINE]]
- [[#vterm][VTERM]]

* ABOUT
Personal config that I use with Doom Emacs.
#+begin_src emacs-lisp
(setq user-full-name "Rajat"
      user-mail-address "rajat241994@gmail.com")
#+end_src

* THEMES AND FONTS
#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
(setq doom-font (font-spec :family "SauceCodePro Nerd Font Mono" :size 13)
      doom-variable-pitch-font (font-spec :family "Monaco" :size 15)
      doom-big-font (font-spec :family "Source Code Pro" :size 24))

(after! doom-themes
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t))
#+end_src

* PRETTIFY SYMBOL
#+begin_src emacs-lisp
(defun my/org-mode/load-prettify-symbols () "Prettify org mode keywords"
  (interactive)
  (setq prettify-symbols-alist
    (mapcan (lambda (x) (list x (cons (upcase (car x)) (cdr x))))
          '(("#+begin_src" . ?)
            ("#+end_src" . ?―)
            ("#+begin_example" . ?)
            ("#+end_example" . ?)
            ("#+DATE:" . ?⏱)
            ("#+AUTHOR:" . ?✏)
            ("[ ]" .  ?☐)
            ("[X]" . ?☑ )
            ("[-]" . ?❍ )
            ("lambda" . ?λ)
            ("#+header:" . ?)
            ("#+name:" . ?﮸)
            ("#+results:" . ?)
            ("#+call:" . ?)
            (":properties:" . ?)
            (":logbook:" . ?))))
  (prettify-symbols-mode 1))
(add-hook 'org-mode-hook #'my/org-mode/load-prettify-symbols)
#+end_src

* ORG MODE
#+begin_src emacs-lisp
(setq org-directory "~/org/")

;; Add keybinding for org-babel-tangle
(map! :after evil-org
      :map evil-org-mode-map
      :localleader
      :desc "Tangle org file"
      :n "B" #'org-babel-tangle)
#+end_src

* GUI TWEAKS
** Line Numbers
Setting line numbers to relative mode.

#+begin_src emacs-lisp
(global-display-line-numbers-mode) ;; only works with emacs >= 26
(setq display-line-numbers-type 'relative)
#+end_src

* FILE SAVE AND LOAD
Enable auto-save by default. And load files automatically when changed.

#+begin_src emacs-lisp

;; Auto-load files when changed
(global-auto-revert-mode t)

;; Auto-save files.
(setq auto-save-default t)
#+end_src

* CUSTOM KEYBINDINGS
#+begin_src emacs-lisp
(map! :desc "Copy till end of line"
      :n "Y" "y$")
(map! :desc "Jump backward"
      :n "[ g" 'evil-jump-backward)
(map! :desc "Jump forward"
      :n "] g" 'evil-jump-forward)
(map! :leader
      :desc "Rename buffer"
      :n "b R" 'rename-buffer)
#+end_src

* EVIL MODE
** Window Split
#+begin_src emacs-lisp
(setq evil-split-window-below t)
(setq evil-vsplit-window-right t)
#+end_src

* FLYSPELL
Used for setting up spell check. Uses `aspell` for dictionary instead of `ispell`
#+begin_src emacs-lisp
(use-package flyspell
  :config
  (setq ispell-program-name "aspell")
  (setq flyspell-prog-text-faces
        (delq 'font-lock-string-face
              flyspell-prog-text-faces))
  (add-hook 'text-mode-hook 'flyspell-mode)
  (add-hook 'prog-mode-hook 'flyspell-prog-mode))
#+end_src

* TREE SITTER
Provides (better) syntax highlighting.
#+begin_src emacs-lisp
(use-package! tree-sitter
  :config
  (require 'tree-sitter-langs)
  (global-tree-sitter-mode)
  (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode))
#+end_src

* SUPER SAVE
Enable auto-save in buffers
#+begin_src emacs-lisp
(use-package super-save
  :ensure t
  :config
  (super-save-mode +1))
#+end_src

* LSP MODE
LSP package for providing syntax completion, checks, etc.
#+begin_src emacs-lisp
(use-package lsp-mode
  :ensure t
  :commands (lsp lsp-deferred)
  :hook (go-mode . lsp-deferred))

(use-package lsp-ui
  :ensure t
  :commands lsp-ui-mode
  :init
)

;;Optional - provides fancier overlays.
(setq lsp-ui-doc-enable nil
      lsp-ui-peek-enable t
      lsp-ui-sideline-enable t
      lsp-ui-imenu-enable t
      lsp-ui-flycheck-enable t)
#+end_src

* PYTHON LSP MS
Microsoft python LSP.
#+begin_src emacs-lisp
(use-package lsp-python-ms
  :ensure t
  :init (setq lsp-python-ms-auto-install-server t)
  :hook (python-mode . (lambda ()
                          (require 'lsp-python-ms)
                          (lsp-deferred))))
#+end_src

* GO LSP (GOPLS)
Go Lang IDE support using gopls.
#+begin_src emacs-lisp
(setq lsp-gopls-staticcheck t)
(setq lsp-eldoc-render-all nil)
(setq lsp-gopls-complete-unimported t)

;;Set up before-save hooks to format buffer and add/delete imports.
;;Make sure you don't have other gofmt/goimports hooks enabled.
(defun lsp-go-install-save-hooks ()
  (add-hook 'before-save-hook #'lsp-format-buffer t t)
  (add-hook 'before-save-hook #'lsp-organize-imports t t))
(add-hook 'go-mode-hook #'lsp-go-install-save-hooks)
#+end_src

* COMPANY
Provides auto completion support, also works with LSP mode.
#+begin_src emacs-lisp

;;Company mode is a standard completion package that works well with lsp-mode.
;;company-lsp integrates company mode completion with lsp-mode.
;;completion-at-point also works out of the box but doesn't support snippets.

(use-package company
  :ensure t
  :config
  (setq company-idle-delay 0)
  (setq company-minimum-prefix-length 1))

(use-package company-lsp
  :ensure t
  :commands company-lsp)

;; disable company mode in eshell (major nuisance)
(setq company-global-modes '(not eshell-mode))
#+end_src

* YASNIPPET
Provides snippet support.
#+begin_src emacs-lisp

;;Optional - provides snippet support.
(use-package yasnippet
  :ensure t
  :commands yas-minor-mode
  :hook (go-mode . yas-minor-mode))
#+end_src

* ESHELL
#+begin_src emacs-lisp
(setq eshell-rc-script (expand-file-name "eshell/profile" doom-private-dir)
      eshell-aliases-file (expand-file-name "eshell/aliases" doom-private-dir)
      eshell-history-file-name (expand-file-name "eshell/history" doom-private-dir)
      eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-kill-on-exit t
      eshell-destroy-buffer-when-process-dies t
      eshell-visual-commands'("bash" "htop" "ssh" "top" "zsh" "less"))

(map! :leader
      :desc "Eshell" "e s" #'eshell
      :desc "Counsel eshell history" "e h" #'counsel-esh-history)
#+end_src

* MODELINE
Configurations for doom modeline.
#+begin_src emacs-lisp
(setq doom-modeline-vcs-max-length 25)
#+end_src

* VTERM
Configuration for the VTerm package.
#+begin_src emacs-lisp
(setq vterm-kill-buffer-on-exit t
      vterm-max-scrollback 5000)
#+end_src
